
--- 
- 
  hosts: all
  tasks: 
    - 
      name: "please install apache"
      yum: "name=httpd state=latest"
    - 
      name: "please start apache"
      service: "name=httpd state=started"
    -
      name: "create kiran user"
      tags: always
      user:
        name: kiran
        groups: root
